// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQgVvZsjN1Jnm4frvDHeXRsCkocv3uEY',
    appId: '1:901854638965:web:8f5e93a2d83b1a41d6993c',
    messagingSenderId: '901854638965',
    projectId: 'firesafety-1e204',
    authDomain: 'firesafety-1e204.firebaseapp.com',
    storageBucket: 'firesafety-1e204.appspot.com', // ✅ fixed
    measurementId: 'G-789W3NSHTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdgVN8MTTZXchfRRPpPP3EonKyBfXpRFk',
    appId: '1:901854638965:android:9039fe11df2aba59d6993c',
    messagingSenderId: '901854638965',
    projectId: 'firesafety-1e204',
    storageBucket: 'firesafety-1e204.appspot.com', // ✅ fixed
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1_qfOscoosPo0FWHJ3KkcZfL5qWNFLfE',
    appId: '1:901854638965:ios:7d2e7190eafd6b3ad6993c',
    messagingSenderId: '901854638965',
    projectId: 'firesafety-1e204',
    storageBucket: 'firesafety-1e204.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.fireSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1_qfOscoosPo0FWHJ3KkcZfL5qWNFLfE',
    appId: '1:901854638965:ios:7d2e7190eafd6b3ad6993c',
    messagingSenderId: '901854638965',
    projectId: 'firesafety-1e204',
    storageBucket: 'firesafety-1e204.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.fireSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZQgVvZsjN1Jnm4frvDHeXRsCkocv3uEY',
    appId: '1:901854638965:web:6ae5762b47a31095d6993c',
    messagingSenderId: '901854638965',
    projectId: 'firesafety-1e204',
    authDomain: 'firesafety-1e204.firebaseapp.com',
    storageBucket: 'firesafety-1e204.appspot.com', // ✅ fixed
    measurementId: 'G-KCGNC7KFX6',
  );
}
