// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'INSERT_YOUR_KEY',
  appId: 'INSERT_YOUR_KEY',
  messagingSenderId: 'INSERT_YOUR_KEY',
  projectId: 'firesafety-1e204',
  authDomain: 'firesafety-1e204.firebaseapp.com',
  storageBucket: 'firesafety-1e204.appspot.com',
  measurementId: 'INSERT_YOUR_KEY',
);

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'INSERT_YOUR_KEY',
  appId: 'INSERT_YOUR_KEY',
  messagingSenderId: 'INSERT_YOUR_KEY',
  projectId: 'firesafety-1e204',
  storageBucket: 'firesafety-1e204.appspot.com',
);

static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'INSERT_YOUR_KEY',
  appId: 'INSERT_YOUR_KEY',
  messagingSenderId: 'INSERT_YOUR_KEY',
  projectId: 'firesafety-1e204',
  storageBucket: 'firesafety-1e204.appspot.com',
  iosBundleId: 'com.example.fireSafetyApp',
);

static const FirebaseOptions macos = FirebaseOptions(
  apiKey: 'INSERT_YOUR_KEY',
  appId: 'INSERT_YOUR_KEY',
  messagingSenderId: 'INSERT_YOUR_KEY',
  projectId: 'firesafety-1e204',
  storageBucket: 'firesafety-1e204.appspot.com',
  iosBundleId: 'com.example.fireSafetyApp',
);

static const FirebaseOptions windows = FirebaseOptions(
  apiKey: 'INSERT_YOUR_KEY',
  appId: 'INSERT_YOUR_KEY',
  messagingSenderId: 'INSERT_YOUR_KEY',
  projectId: 'firesafety-1e204',
  authDomain: 'firesafety-1e204.firebaseapp.com',
  storageBucket: 'firesafety-1e204.appspot.com',
  measurementId: 'INSERT_YOUR_KEY',
);

}
